/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/exercises': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Exercises */
    get: operations['list_exercises_api_v1_exercises_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/exercises/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Exercise */
    get: operations['get_exercise_api_v1_exercises__slug__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/onboarding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Onboarding */
    get: operations['onboarding_api_v1_onboarding_get'];
    put?: never;
    /** Submit */
    post: operations['submit_api_v1_onboarding_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/plans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Plan */
    get: operations['plan_api_v1_plans_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/plans/today': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Today Plan */
    get: operations['today_plan_api_v1_plans_today_get'];
    put?: never;
    /** Complete Today Plan */
    post: operations['complete_today_plan_api_v1_plans_today_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/plans/today/feedback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Today Plan Feedback */
    post: operations['submit_today_plan_feedback_api_v1_plans_today_feedback_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profile */
    get: operations['profile_api_v1_profile_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CompleteTodayExerciseRequest */
    CompleteTodayExerciseRequest: {
      /** Exerciseid */
      exerciseId: string;
    };
    /** CurrentPlan */
    CurrentPlan: {
      /** Profileid */
      profileId: string;
      level: components['schemas']['Level'];
      planLevel: components['schemas']['Level'];
      volumeTier: components['schemas']['VolumeTier'];
      /** Cycledays */
      cycleDays: number;
      /** Workouts */
      workouts: components['schemas']['PlanWorkout'][];
    };
    /** ExerciseList */
    ExerciseList: {
      /** Data */
      data: components['schemas']['ExercisePublic'][];
    };
    /** ExercisePublic */
    ExercisePublic: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Bodyregion */
      bodyRegion: string;
      /** Movementpattern */
      movementPattern: string;
      /** Difficulty */
      difficulty: number;
      /** Level */
      level: string;
      /** Gif */
      gif: string;
      /** Instructions */
      instructions: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * Level
     * @enum {string}
     */
    Level: 'foundation' | 'beginner' | 'intermediate' | 'advanced';
    /** OnboardingOption */
    OnboardingOption: {
      /** Id */
      id: string;
      /** Label */
      label: string;
    };
    /** OnboardingQuestion */
    OnboardingQuestion: {
      /** Id */
      id: string;
      /**
       * Type
       * @enum {string}
       */
      type: 'text' | 'select' | 'multi_select';
      /** Label */
      label: string;
      /** Hint */
      hint?: string | null;
      /** Hintsummary */
      hintSummary: string;
      /** Hintdescription */
      hintDescription: string;
      /**
       * Required
       * @default true
       */
      required: boolean;
      /** Options */
      options?: components['schemas']['OnboardingOption'][];
    };
    /** OnboardingRequest */
    OnboardingRequest: {
      /** Answers */
      answers: {
        [key: string]: string | string[];
      };
    };
    /** OnboardingResponse */
    OnboardingResponse: {
      /**
       * Status
       * @enum {string}
       */
      status: 'in_progress' | 'completed';
      /** Questions */
      questions?: components['schemas']['OnboardingQuestion'][];
      profile?: components['schemas']['ProfilePublic'] | null;
    };
    /** PlanAdjustmentAssessment */
    PlanAdjustmentAssessment: {
      /**
       * Action
       * @enum {string}
       */
      action: 'keep_plan' | 'reduce_volume' | 'increase_volume' | 'repeat_level' | 'flag_pain';
      /**
       * Confidence
       * @enum {string}
       */
      confidence: 'low' | 'medium' | 'high';
      /** Rationale */
      rationale: string;
    };
    /** PlanExercise */
    PlanExercise: {
      /** Exerciseid */
      exerciseId: string;
      /** Slug */
      slug: string;
      /** Name */
      name: string;
      /** Movementpattern */
      movementPattern: string;
      /** Gif */
      gif: string;
      /** Instructions */
      instructions: string;
      /** Sets */
      sets: number;
      /** Reps */
      reps?: string | null;
      /** Holdseconds */
      holdSeconds?: string | null;
      /** Restseconds */
      restSeconds: number;
    };
    /** PlanFeedbackRequest */
    PlanFeedbackRequest: {
      /**
       * Rating
       * @enum {string}
       */
      rating: 'too_hard' | 'manageable' | 'easy' | 'pain' | 'skipped';
      /** Note */
      note?: string | null;
    };
    /** PlanFeedbackResponse */
    PlanFeedbackResponse: {
      plan: components['schemas']['TodayPlan'];
      assessment?: components['schemas']['PlanAdjustmentAssessment'] | null;
    };
    /** PlanWorkout */
    PlanWorkout: {
      /** Day */
      day: number;
      /** Title */
      title: string;
      /** Exercises */
      exercises: components['schemas']['PlanExercise'][];
    };
    /** ProfilePublic */
    ProfilePublic: {
      /** Profileid */
      profileId: string;
      level: components['schemas']['Level'];
      currentPlanLevel: components['schemas']['Level'];
      currentVolumeTier: components['schemas']['VolumeTier'];
      /** Onboarded */
      onboarded: boolean;
      /** Streak */
      streak: number;
    };
    /** TodayPlan */
    TodayPlan: {
      /** Profileid */
      profileId: string;
      level: components['schemas']['Level'];
      planLevel: components['schemas']['Level'];
      volumeTier: components['schemas']['VolumeTier'];
      /** Day */
      day: number;
      /** Completed */
      completed: boolean;
      /** Completedexerciseids */
      completedExerciseIds: string[];
      workout: components['schemas']['PlanWorkout'];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VolumeTier
     * @enum {string}
     */
    VolumeTier: 'low' | 'medium' | 'high';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: boolean;
          };
        };
      };
    };
  };
  list_exercises_api_v1_exercises_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExerciseList'];
        };
      };
    };
  };
  get_exercise_api_v1_exercises__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExercisePublic'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  onboarding_api_v1_onboarding_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OnboardingResponse'];
        };
      };
    };
  };
  submit_api_v1_onboarding_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OnboardingResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  plan_api_v1_plans_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentPlan'];
        };
      };
    };
  };
  today_plan_api_v1_plans_today_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TodayPlan'] | null;
        };
      };
    };
  };
  complete_today_plan_api_v1_plans_today_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompleteTodayExerciseRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TodayPlan'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_today_plan_feedback_api_v1_plans_today_feedback_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PlanFeedbackRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlanFeedbackResponse'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  profile_api_v1_profile_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProfilePublic'];
        };
      };
    };
  };
}
